#This playbook will install elasticsearch in ubuntu 12.04
---
- hosts: web
  tasks:
   - name: Install gcc build essentials
     apt: pkg=build-essential 
   
   - name: Install python dev environment
     apt: pkg=python-dev
   
   - name: Install python-pip
     apt: pkg=python-pip
 
   - name: Install git
     apt: pkg=git

   - name: Install software-properties
     apt: pkg=software-properties-common

   - name: Install python software properties
     apt: pkg=python-software-properties

   - name: Update cache
     apt: update_cache=true

   - name: Add repository 
     apt_repository: repo='ppa:webupd8team/java' state=present
     register: ppajava

   - name: Accept licence for java
     shell: echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections 
